### PR TITLE
Allow a module to trigger the publishing of its own assets

### PR DESCRIPTION
**Pull request by sroutier**
Follow up to my previous PRs.

The current method available to publish assets relies solely on the artisan command which has 2 inconvenient:
1) It cannot be automated nicely from the module itself.
2) The current publishing method applies to the assets of all modules, and if the force method is used all assets will be overwritten.

This latest path maintains the original artisan method to publish assets but also adds a method that gets triggered by default during the initialize call to allow each module to participate and trigger the publishing of its own assets if any exist.

Let me know what you think.
Cheers.
/S

### CODE REVIEW

**Comment by kaidesu** [comment]
Thanks for these pull requests - may take me a few days but I'll be reviewing the code before taking action on anything.

**Comment by sroutier** [comment]
👍

**Comment by Nowi5** [comment]
Any progress on this?

**Comment by kaidesu** [comment]
Going to hold off on this.

**Pull request closed without merging**
